before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: uniac
    main: ./cmd/uniac/main.go

archives:
  - formats: [ 'tar.gz' ]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'